[package]
name = "hello_rust"
version = "0.1.0"
authors = ["Waleed Samy <waleedsamygd@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.4.0"

[[bin]]
name = "main2"
test = false
bench = false

[[bin]]
name = "rectangle"
test = false
bench = false